## Lesson 2: How to Transform Data for Time Series
* Sliding Window transformation

In [77]:
def sliding_window(li, step):
    import numpy as np
    idx = [(i, i+step) for i in range(0, len(li)-step)]
    X = []
    y = []
    for i, j in idx:
        X.append(li[i:j])
        y.append(li[j])
    return np.array(X), np.array(y)

In [79]:
import pandas as pd
df = pd.read_csv('data/daily-total-female-births.csv')
b = df.sort_values('Date')['Births'].values
X, y = sliding_window(b, 3)
print(X[:10])
print(y[:10])

[[35 32 30]
 [32 30 31]
 [30 31 44]
 [31 44 29]
 [44 29 45]
 [29 45 43]
 [45 43 38]
 [43 38 27]
 [38 27 38]
 [27 38 33]]
[31 44 29 45 43 38 27 38 33 55]
